<?php
/**
 * CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetailsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Cashfree
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cashfree Payout APIs
 *
 * Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2024-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cashfree\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description It should contain the contact details of the beneficiary.
 * @package     Cashfree
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails"
     */
    public function testCreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "beneficiary_email"
     */
    public function testPropertyBeneficiaryEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "beneficiary_phone"
     */
    public function testPropertyBeneficiaryPhone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "beneficiary_country_code"
     */
    public function testPropertyBeneficiaryCountryCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "beneficiary_address"
     */
    public function testPropertyBeneficiaryAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "beneficiary_city"
     */
    public function testPropertyBeneficiaryCity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "beneficiary_state"
     */
    public function testPropertyBeneficiaryState()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "beneficiary_postal_code"
     */
    public function testPropertyBeneficiaryPostalCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
