<?php
/**
 * CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetailsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Cashfree
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cashfree Payout APIs
 *
 * Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2024-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cashfree\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description It should contain the card details of the beneficiary.
 * @package     Cashfree
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetails"
     */
    public function testCreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "card_token"
     */
    public function testPropertyCardToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "card_network_type"
     */
    public function testPropertyCardNetworkType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "card_cryptogram"
     */
    public function testPropertyCardCryptogram()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "card_token_expiry"
     */
    public function testPropertyCardTokenExpiry()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "card_type"
     */
    public function testPropertyCardType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "card_token_pan_sequence_number"
     */
    public function testPropertyCardTokenPanSequenceNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
